name: learningx_api
description: Canvas/LearningX API client for SSU assignment deadline alerts.
version: 0.0.1

environment:
  sdk: ^3.11.1

resolution: workspace

dependencies:
  dio: ^5.9.0
  json_annotation: ^4.11.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  test: ^1.25.15
